### PR TITLE
examples: Fix compilation error in transcode

### PR DESCRIPTION
**Pull request by infinityb**
Hi,

I noticed one of your examples were broken by 993164f3d726fd1ee1da63ae7e714301b7815136 so I've updated it to compile.

Regards,
Stacey Ell

### CODE REVIEW

**Comment by 3d0c** [comment]
Ok, Thanks.
